/* Generated by autorevision - do not hand-hack! */
#ifndef AUTOREVISION_H
#define AUTOREVISION_H

#define VCS_TYPE		"git"
#define VCS_BASENAME	"FYP"
#define VCS_UUID		"84f2fddf8c3b5254f0acdcff07ed4736839cb85f"
#define VCS_NUM			10
#define VCS_DATE		"2019-10-10T22:45:45Z"
#define VCS_BRANCH		"master"
#define VCS_TAG			""
#define VCS_TICK		10
#define VCS_EXTRA		""

#define VCS_ACTION_STAMP	"2019-10-10T22:45:45Z!natlivsey@gmail.com"
#define VCS_FULL_HASH		"ac706edfd7d48e8405bc896012fd570e105e1cd8"
#define VCS_SHORT_HASH		"ac706edf"

#define VCS_WC_MODIFIED		1

#endif

/* end */
