/*
 * generated by Xtext 2.20.0
 */
package fyp.xtext.wesnoth.mydsl;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class WesnothDSLRuntimeModule extends AbstractWesnothDSLRuntimeModule {
}
