/**
 * generated by Xtext 2.21.0
 */
package org.xtext.wesnoth.wail;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Conditional</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.wesnoth.wail.Conditional#getX <em>X</em>}</li>
 * </ul>
 *
 * @see org.xtext.wesnoth.wail.WailPackage#getConditional()
 * @model
 * @generated
 */
public interface Conditional extends EObject
{
  /**
   * Returns the value of the '<em><b>X</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>X</em>' containment reference.
   * @see #setX(whenRules)
   * @see org.xtext.wesnoth.wail.WailPackage#getConditional_X()
   * @model containment="true"
   * @generated
   */
  whenRules getX();

  /**
   * Sets the value of the '{@link org.xtext.wesnoth.wail.Conditional#getX <em>X</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>X</em>' containment reference.
   * @see #getX()
   * @generated
   */
  void setX(whenRules value);

} // Conditional
