/*
 * generated by Xtext 2.20.0
 */
package fyp.xtext.wesnoth.mydsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class WesnothDSLUiModule extends AbstractWesnothDSLUiModule {

	public WesnothDSLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
