/*
 * generated by Xtext 2.21.0
 */
package org.xtext.wesnoth.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.wesnoth.ui.internal.WesnothActivator;

public class WailUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return WesnothActivator.getInstance().getInjector("org.xtext.wesnoth.Wail");
	}

}
