/**
 * generated by Xtext 2.20.0
 */
package fyp.xtext.wesnoth.mydsl.wesnothDSL.impl;

import fyp.xtext.wesnoth.mydsl.wesnothDSL.WesnothDSLPackage;
import fyp.xtext.wesnoth.mydsl.wesnothDSL.whenRules;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>when Rules</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class whenRulesImpl extends MinimalEObjectImpl.Container implements whenRules
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected whenRulesImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return WesnothDSLPackage.Literals.WHEN_RULES;
  }

} //whenRulesImpl
