/**
 * generated by Xtext 2.20.0
 */
package fyp.xtext.wesnoth.mydsl.wesnothDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Defualt CA</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fyp.xtext.wesnoth.mydsl.wesnothDSL.Defualt_CA#getCaType <em>Ca Type</em>}</li>
 * </ul>
 *
 * @see fyp.xtext.wesnoth.mydsl.wesnothDSL.WesnothDSLPackage#getDefualt_CA()
 * @model
 * @generated
 */
public interface Defualt_CA extends EObject
{
  /**
   * Returns the value of the '<em><b>Ca Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ca Type</em>' attribute.
   * @see #setCaType(String)
   * @see fyp.xtext.wesnoth.mydsl.wesnothDSL.WesnothDSLPackage#getDefualt_CA_CaType()
   * @model
   * @generated
   */
  String getCaType();

  /**
   * Sets the value of the '{@link fyp.xtext.wesnoth.mydsl.wesnothDSL.Defualt_CA#getCaType <em>Ca Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ca Type</em>' attribute.
   * @see #getCaType()
   * @generated
   */
  void setCaType(String value);

} // Defualt_CA
