/**
 * generated by Xtext 2.20.0
 */
package fyp.xtext.wesnoth.mydsl.wesnothDSL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Rule</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fyp.xtext.wesnoth.mydsl.wesnothDSL.Rule#getName <em>Name</em>}</li>
 *   <li>{@link fyp.xtext.wesnoth.mydsl.wesnothDSL.Rule#getUnitID <em>Unit ID</em>}</li>
 *   <li>{@link fyp.xtext.wesnoth.mydsl.wesnothDSL.Rule#getBehaviours <em>Behaviours</em>}</li>
 * </ul>
 *
 * @see fyp.xtext.wesnoth.mydsl.wesnothDSL.WesnothDSLPackage#getRule()
 * @model
 * @generated
 */
public interface Rule extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see fyp.xtext.wesnoth.mydsl.wesnothDSL.WesnothDSLPackage#getRule_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link fyp.xtext.wesnoth.mydsl.wesnothDSL.Rule#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Unit ID</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Unit ID</em>' containment reference.
   * @see #setUnitID(UnitID)
   * @see fyp.xtext.wesnoth.mydsl.wesnothDSL.WesnothDSLPackage#getRule_UnitID()
   * @model containment="true"
   * @generated
   */
  UnitID getUnitID();

  /**
   * Sets the value of the '{@link fyp.xtext.wesnoth.mydsl.wesnothDSL.Rule#getUnitID <em>Unit ID</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Unit ID</em>' containment reference.
   * @see #getUnitID()
   * @generated
   */
  void setUnitID(UnitID value);

  /**
   * Returns the value of the '<em><b>Behaviours</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Behaviours</em>' attribute list.
   * @see fyp.xtext.wesnoth.mydsl.wesnothDSL.WesnothDSLPackage#getRule_Behaviours()
   * @model unique="false"
   * @generated
   */
  EList<String> getBehaviours();

} // Rule
