/**
 * generated by Xtext 2.20.0
 */
package fyp.xtext.wesnoth.mydsl.wesnothDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>when Rules</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see fyp.xtext.wesnoth.mydsl.wesnothDSL.WesnothDSLPackage#getwhenRules()
 * @model
 * @generated
 */
public interface whenRules extends EObject
{
} // whenRules
